theme = "darcula-solid"

[editor]
# line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

# dvorak
[keys.normal]
Cmd-s = ":write"
Cmd-C-r = [":write", ":config-reload"]
space.q = ":q"


[keys.insert]
C-b = "move_char_left"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"

S-right = "extend_char_right"
S-left = "extend_char_left"
S-up = "extend_line_up"
S-down = "extend_line_down"
Cmd-c = "yank_to_clipboard"

C-right = "move_next_word_start"
C-left = "move_prev_word_end"

# Ctrl+Shift+矢印でワード単位選択
C-S-right = "extend_next_word_start"
C-S-left = "extend_prev_word_end"

# [keys.select]
# S-right = "extend_char_right"
# S-left = "end_char_left"
# S-up = "extend_line_up"
# S-down = "extend_line_down"
# C-right = "extend_next_word_start"
# C-left = "extend_prev_word_end"
